### ISSUE TITLE
Custom icon not visible in main contextual menu

### ISSUE THREAD

**Issue by Dundes** [clechasseur/pathcopycopy#110]
simply... having an icon close to the main feature used, right clicking on a file, it helps to quickly put in evidence this one; I'd love this feature
Thanks

![IMG_20200222_184102](https://user-images.githubusercontent.com/61359194/75096767-1e9f2d80-55a3-11ea-96d2-43e469081d08.png)

**Comment by clechasseur** [comment]
You can already do this with the Settings application. In the _Commands_ tab, click in the _Icon_ column next to the command you want and set an icon file. You can also Shift-click to use the default icon.

![explorer_43pcdGKICT](https://user-images.githubusercontent.com/1435551/75100794-a2a3e600-55a0-11ea-9d8e-fc35ab430380.png)

**Comment by Dundes** [comment]
thank you for quick answer Charles
Icon is visible next into submenu, but not the first level menu, not directly right clicking a file or a folder

**Comment by clechasseur** [comment]
Hmm, that's strange, it should show up in both menus, sounds like a bug. I'll look into it.

**Comment by clechasseur** [comment]
I checked the code and found the issue. It only happens when the only command selected in the main menu is "Copy Long Path".

I'll leave this open so I can fix it. In the meantime, there's a kind of workaround. Using `regedit`, navigate to the `HKEY_CURRENT_USER\Software\clechasseur\PathCopyCopy` key and create the following value:

Name: UseIconForDefaultPlugin
Type: REG_DWORD
Value: 1

That should instruct Path Copy Copy to display the default icon for any command in the main menu. This setting is not editable via the Settings application, so to turn it off you need to go back and delete the value.

**Comment by Dundes** [comment]
Thanks for the workaround; I checked, the solution works, but the icon shown is not the one chosen but the default one; thanks again :-)

![IMG_20200224_201411](https://user-images.githubusercontent.com/61359194/75183212-54c6e380-5742-11ea-8ab2-704ff49b2dcc.png)

**Comment by clechasseur** [comment]
> Thanks for the workaround; I checked, the solution works, but the icon shown is not the one chosen but the default one; thanks again :-)

Yeah, it's not ideal. There's another trick I thought of, though:

1. Create a new custom command based on "Copy Long Path".
2. Assign an icon to it.
3. Select that command instead of "Copy Long Path" in the main menu.

That should give you the icon you want.

**Comment by Dundes** [comment]
sorry, I do not want to trouble, trick does not seems to work... icon still the same, but I can wait fix in the next rel...

my best compliments for the very useful tool

![IMG_20200224_215452](https://user-images.githubusercontent.com/61359194/75190703-2dc3de00-5751-11ea-869f-fb239e19f892.png)

**Comment by clechasseur** [comment]
Sorry that didn't work. I'm out of ideas then, you will have to wait for a fix 😞

**Comment by clechasseur** [comment]
This issue has been fixed and will be available in the next version.
