### ISSUE TITLE
[FEATURE] Remove the \ from the end of paths in the options

### ISSUE THREAD

**Issue by stephen147** [clechasseur/pathcopycopy#116]
It would be nice to have a checkbox in the setting to remove the last `\` from any paths.

so :
`Z:\Path to a folder\goes here\`

to:
`Z:\Path to a folder\goes here`

**Comment by clechasseur** [comment]
Forgot to ask back then but - which command leaves a `\` at the end of the path? I thought that never happened...

**Comment by stephen147** [comment]
Hi, sorry for the delay in getting back to you.

It's the **Copy Long Parent Folder Path**

I know I can create my own but it would be nice to enable removing the last slash in the options.

**Comment by clechasseur** [comment]
Ok, I double-checked the code because I wasn't sure and it's been a while since I've used this 😄 

There is already an option that controls this:

![PathCopyCopySettings_1WdVqgiyPO](https://user-images.githubusercontent.com/1435551/86522937-2e712d00-be33-11ea-9723-2c7ca4c1b08c.png)

If this is selected, the directory paths (including those copied by the _Long Parent Folder Path_ command) will always have a trailing separator. So simply unselect this and you'll be fine. 👍

**Comment by stephen147** [comment]
Thanks for that.
