### ISSUE TITLE
[BUG] Follow symlink does not work for directory content

### ISSUE THREAD

**Issue by jackhab** [clechasseur/pathcopycopy#118]
**Describe the bug**
When network location is accessed via symbolic link its path is not expanded as in the case when the same location is accessed via network drive.

**To Reproduce**
Map a network location via symbolic link in command line:
`mklink /d LinkedPath \\server\some\path`
Explorer > right click LinkedPath > Path Copy > Examine the UNC path
Provided UNC path is \\%LOCAL-COMPUTER-NAME%\LinkedPath

**Expected behavior**
Provided UNC path must be \\\\server\some\path

**Software**
 - OS: Windows 10
 - Path Copy Copy Version 17.0

**Comment by clechasseur** [comment]
So I took some time replying to this because I no longer have access to a network environment to test UNC paths, but in retrospect I think this has nothing to do with network paths.

I suggest you update to Path Copy Copy 18.0 and use the new "Follow symlink" custom command element support. Here is an exported command that is based on "Copy Long UNC Path", but with symlink support:

[LongUNCPath_symlink.zip](https://github.com/clechasseur/pathcopycopy/files/4596492/LongUNCPath_symlink.zip)

Let me know if it works for you.

**Comment by jackhab** [comment]
Hi Charles 
it does not work. I verified in command line (cmd and powershell) the symlink target points to the server path.

**Comment by clechasseur** [comment]
Interesting twist. 😉 
I'll look into it.

**Comment by jackhab** [comment]
Thanks. I checked it again and I'd like to add that even Windows reports symlink target only for the symlink directory and not for its contents both in cmd dir and Explorer's file properties so it would be super cool to have such feature!

**Comment by clechasseur** [comment]
This bug has been fixed. From now on, symbolic links that are part of the path (and not just its target) will be correctly followed. This will be available in the next version.
