### ISSUE TITLE
[BUG] For .lnk files, the position of "Path Copy" in context menu depends on option "Copy paths of shortcut..."

### ISSUE THREAD

**Issue by MMiloslavsky** [clechasseur/pathcopycopy#119]
**Description**
If "Copy paths of shortcut..." is checked, "Path Copy" moves to the top of context menu.

**To Reproduce**
1. Right-click on any .lnk file.
2. Note that "Path Copy" is located at the bottom of context menu.
3. Go to the Settings => Options tab.
4. Check the option "Copy paths of shortcut (.lnk) files themselves", and click OK button.
5. Right-click on any .lnk file again.
6. Result: "Path Copy" location in context menu has moved from the bottom to the top.

**Expected behavior**
The location of "Path Copy" in context menu should be permanent.
Better, if user could select that permanent location via additional setting on Options tab (see [Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/shell/context-menu-handlers#specifying-the-position-and-order-of-static-verbs)).

**Screenshots**
![Off](https://user-images.githubusercontent.com/43003302/81446437-8e28c000-9183-11ea-9130-bc256abc7592.png)
![image](https://user-images.githubusercontent.com/43003302/81447078-a3521e80-9184-11ea-8c37-e655700a7d1a.png)

**Software:**
 - OS: Windows 10 x64 Home 1909 build 18363.815
 - Path Copy Copy: v18.0

**Additional context**
[Related issue](https://github.com/clechasseur/pathcopycopy/issues/7).

Doesn't help:

- Total reinstall, including manually cleaning the disk and registry from "PathCopy" and "Path Copy".
- Installation for all users or just for me.
- Installation on clean virtual machine.

By the way, it would be good idea to replace the option "Copy paths of shortcut (.lnk) files themselves" with two items on Commands tab: "Copy Shortcut Path" and "Copy Shortcut Target Path".

**Comment by clechasseur** [comment]
Copying path of shortcuts themselves is kinda tricky because it involves two instances of the shell extension. The second instance is the one that will be used when copying the path of a shortcut. Because of this I cannot control the position of the instances in the menu. This also makes it impossible to toggle between the two choices using two commands.

The documentation you linked to concerns static verbs - those defined by registry entries only. This is not the case with Path Copy Copy as its dynamic nature precludes the use of the registry only. I do not know of a way to specify the position of the menu items in the contextual menu for dynamic extensions like Path Copy Copy.
