### ISSUE TITLE
[BUG] Not recognising valid regex

### ISSUE THREAD

**Issue by jonnywright** [clechasseur/pathcopycopy#144]
**Describe the bug**
I have created a regex which passes in regex builder [regex101](https://regex101.com/) but gets flagged as invalid in Path Copy Copy. The regex is `(?<=\w\:\\(\w|\d|\s|\.)*\\)(\w|\.|\d|\s)+` and is designed to replace the second level in a file path.

**To Reproduce**
1. Create new custom command
2. Find/replace, tick _Use regular expressions_ and click _Test regex_
3. Enter regular expression `(?<=\w\:\\(\w|\d|\s|\.)*\\)(\w|\.|\d|\s)+` and click _Test_

**Expected behavior**
Expect the second level of the sample path to be replaced.

**Screenshots**
N/A

**Software (please complete the following information):**
 - OS: Windows 10 Ent 1909
 - Path Copy Copy Version 19.0

**Additional context**
Have tried with various other slightly varied regex with no joy.

**Comment by clechasseur** [comment]
This is because you're using lookbehind in your regex, which is not supported by the EMCAScript engine used by Path Copy Copy. You can find a bit more information on what is and what isn't supported by the Path Copy Copy regex engine here:

http://www.regular-expressions.info/javascript.html

According to this page, lookbehind is now part of the ECMAScript specification, but it doesn't seem like it's supported by the Microsoft C++ runtime yet. Maybe we'll get support in a future version.

(Sorry for the lag in the response 😄 )
