### ISSUE TITLE
Suspicious installation file

### ISSUE THREAD

**Issue by djhurio** [clechasseur/pathcopycopy#15]
I am not able to install the latest (14) version of the software because Symantec antivirus considers it as suspicious. The previous version (13.0.1) is good regarding this.

**Comment by clechasseur** [comment]
Funny, I have an antivirus by Symantec too and it doesn't complain. Must depend on the definition files.

As mentioned elsewhere, this is most likely a false positive and I have very little control over those. Here's a report by VirusTotal on the installer, mentioning two false positives (again, nothing from Symantec):
https://www.virustotal.com/fr/file/851475cd14e2b7ccef0bb778766affb00cc76512d77f06984aba4373a784c241/analysis/

I hope you can get around the antivirus somehow, because there's not much I can do... Or perhaps wait for them to change the definition files again.
