### ISSUE TITLE
Error while installing on Windows XP SP3

### ISSUE THREAD

**Issue by Virgus** [clechasseur/pathcopycopy#17]
Hello,
I just tried to install the latest release on WinXP SP3 and got the following error:
"Error loading PCC32.dll - Invalid access to memory location."
I can run the PathCopyCopySettings.exe but the error continues to pop up.

It would be great to make it work on XP too
as your tool is really useful, thanks!

![pathcopycopy](https://user-images.githubusercontent.com/6388217/29750008-f109cf8e-8b37-11e7-9255-57cdeff1d3eb.png)

**Comment by clechasseur** [comment]
Hmm. It's supposed to work on WinXP, at least that's what I thought :P It's been a long while since I've tried it on WinXP and I no longer have access to a 32-bit installation of WinXP to test this on...

To be honest, I was keeping the advertisement for WinXP compatibility because it was "free" so to speak, but as WinXP is no longer officially supported, I'm not sure it's worth the trouble... Using an outdated, no longer supported OS seems dangerous to me...

Anyone has access to a 32-bit WinXP installation and is able to remote debug this to help me out? :-)

**Comment by careca1970** [comment]
Same problem here.
I will keep prior version...

**Comment by clechasseur** [comment]
[Version 14.0.1](https://github.com/clechasseur/pathcopycopy/releases/tag/v14.0.1) restores compatibility with Windows XP. XP users are encouraged to upgrade; the release will be pushed via software update soon.
