### ISSUE TITLE
Bug: Copy UNC Parent Folder Path does not work with network mapped drives

### ISSUE THREAD

**Issue by thedoctrine101** [clechasseur/pathcopycopy#54]
I have this network drive mapped to the following path: **_\\ServerName\E$\media_**
This network location is mapped to drive (E:)
When right-clicking drive (E:) and using PathCopyCopy's _**Copy UNC Parent Folder Path**_ function directly on the mapped drive icon, logically, in this case, it should copy the path **_\\ServerName\E$_** to the clipboard since it is the UNC Parent Folder of **_\\ServerName\E$\media_**

Well in this case, it does NOT. It only copies the drive letter as is, so **_E:_** in this case. So just the letter and the colon, thats it. I do not know if PathCopyCopy is like this by design, but I think this is an issue.

FYI, the paths do have the double slashes, but for some reason, it only shows one once I save my comment.

**Comment by clechasseur** [comment]
I can sorta reproduce this. Can you validate this: is `\\ServerName\E$` a valid share in itself? If you try to open it, does it work?

**Comment by thedoctrine101** [comment]
Yes, it is absolutely a valid share.

**Comment by clechasseur** [comment]
I know what's happening. It's not a "bug" in the sense that it is coded to work this way, but I agree that it is misleading. I will fix it.

**Comment by thedoctrine101** [comment]
Well technically the E: drive is the Parent Folder Path, but not the UNC Parent Folder Path

**Comment by thedoctrine101** [comment]
Well, you seem to know how to make it work. Overall though, you developed a good product here. Props.

**Comment by clechasseur** [comment]
Okay, I've had a bit more time to toy with this and ponder the implications. I have decided to leave this as-is. Changing it would be a breaking change, since it changes the core implementation - even if a little misleading.

In order to do what you want, it's possible to create a custom command. Choose "Copy Long UNC Path" as Base Command and in Find/Replace, choose "Use regular expressions" and enter the following expression:

Find what: `^(.*)(\\|/)[^\\/]+(\\|/)?$`
Replace with: `$1`

This should achieve the result you want.

**Comment by thedoctrine101** [comment]
Charles, I did as you suggested and it works, so I think this is perfectly fine. A bit unorthodox, but works as required. Its a good workaround, and since its a custom command, I just named it "Copy Mapped Drive UNC Parent Folder Path". So it still all makes sense.
