### ISSUE TITLE
How start  without  install  ?

### ISSUE THREAD

**Issue by selevo** [clechasseur/pathcopycopy#66]
I  reinstall my OS

I not see exe  file in folder,  same PathCopyCopy.exe e.g..
i only see
PathCopyCopyCOMPluginExecutor32.exe
PathCopyCopyCOMPluginExecutor64.exe
PathCopyCopyRegexTester.exe
PathCopyCopySettings.exe

but   this not   pathcopycopy   after  run this  files

**Comment by clechasseur** [comment]
Path Copy Copy is a shell extension - an extension for Windows Explorer and similar applications. It has no EXE file because you cannot use it standalone. The Path Copy Copy code is stored in DLLs called `PCC32.dll` and `PCC64.dll`.

If you reinstalled your OS, the easiest way to get back Path Copy Copy functionality is to reinstall with the installer. You can reinstall over your existing files. This will re-register the DLLs and give you access to the Path Copy Copy contextual menu.
