### ISSUE TITLE
Get path of actual shortcut

### ISSUE THREAD

**Issue by clechasseur** [clechasseur/pathcopycopy#7]
Add an option to get the path of the actual shortcut (the .lnk file) instead of following the link.

Original issue: https://pathcopycopy.codeplex.com/workitem/11417

**Comment by MMiloslavsky** [comment]
It should also be possible to get the path of Internet shortcut (the .url file).

**Comment by garoto** [comment]
`.url` files are plain ASCII files, so to implement that would require file parsing routines. Seems way out of scope to me.

**Comment by clechasseur** [comment]
.url files are a separate issue, I'll open a new one.

**Comment by clechasseur** [comment]
URL issue moved to #77.

**Comment by blackcrack** [comment]
this becomes me a suggestion would it also, if url's (so the copy adressbar or path's from copy'ed fileadresses) create a link on the fs.. with the addresses from the clibboard http:\\*, http:\\* or c::\\, create .lnk or .url
then can you copy the path of the iadress or file, can klick on the Desktop or anywhere in the Filemanager with right mouseklick => patchcopycopy=>create a link(lnk/url) therewith can you use the algoryghm of the explorer (if you found the code) "copy path of the inet/url" rightklick on the desktop=>new=>link, this can you make more effective, copy the the last clipboard entry, 
and clipboardtext>link->create the link/url with( (config entry [X]popup by Linkcreation"get the name:" // as enhanced possibility )
otherwise could the url/lnk=The name and later could the user rename the fresh generate link.

this is more effective as the MS-Method of create a link 

Copy url/F-path/file+path 
MS-method: 
right click on desktop : new->link=popup->popup....popup

pathcopycopy:
In any Folder (inkl. Desktop) 
right click on desktop/free space of the Filemanager : 
"New Link from CBoard"-> create/put a link from last C-Entry" (From Clibboard)

doingh->exist fastest as possible- it brings on the point "Put a link on filesystem"
last entry with file:\\, http:\\ and html:\\ and \\ (because Sambafs)
so all texts with "\\" in the adresses in the last line of Clipboard.. i guess this could works.

i think on copyed texts with a \\this is a text there could insert a check-coutine
"exist this file or url actually" =check the adress if become a "1" then create else [goto :eof)

there could also be a possibility for ftp, sftp with passwords to open in explorer... if, this works....
or, a dll where supports some to connecting a ftp/sftp folder with "Name"&"pword"@ftp:\\url.co\path

gives there in the outer space in the internet a ftpsfs.dll or something ? could be cool !

best regards
Blacky

**Comment by MMiloslavsky** [comment]
Thanks a lot for implementing the ".url file" enhancement in v17.0.
Any chance to address the ".lnk file" enhancement as well?

**Comment by clechasseur** [comment]
> Thanks a lot for implementing the ".url file" enhancement in v17.0.
> Any chance to address the ".lnk file" enhancement as well?

This one is not as easy. We'll see what I can do.

**Comment by clechasseur** [comment]
I suspect it could be possible if I used the `SHCreateShellItemArrayFromDataObject` function in `IShellExtInit::Initialize` instead of using `CF_HDROP / DragQueryFile`. However, this is only available on Windows Vista, so we'll have to shelf this one for later.

**Comment by clechasseur** [comment]
This has been implemented in the `feature/post-winxp` branch and will be part of the next major release.

I'm wondering if this setting should default to ON… maybe it makes more sense to get the path of the .lnk file you clicked on...

**Comment by MMiloslavsky** [comment]
Thanks a lot for implementing this long-awaited feature!

For me, the default state of this setting doesn't matter, as long as it could be easily changed at any moment in the Settings. Probably, it's a good idea to leave it OFF by default, to keep the behavior of previous releases.
