### ISSUE TITLE
Expert mode doesn't keep the sequence

### ISSUE THREAD

**Issue by BaWue** [clechasseur/pathcopycopy#88]
Thanks for the new Version 17.0.1 and the excellent Expert Mode!

However I got an example custom command in which the Expert Mode forgets about the sequence of elements created using the up an down arrows.

The element sequence in which this occurs consists of 4 elements:
1. Use Base Command: Copy Long Path
2. Turn Backslashes Into Forward Slashes
3. Remove File Extension
4. Find / Replace Using Regular Expressions: Regular expression: "a", Replacement expression: "b", Ignore case: yes

![Unbenannt](https://user-images.githubusercontent.com/55134147/64601223-d3aaa880-d3bc-11e9-94b2-cf6d746565ee.png)

After clicking "OK" and then "Edit ..." again and switching into Expert Mode, the element No. 4: "Find / Replace Using Regular Expressions" has been moved to position 2:

![Unbenannt1](https://user-images.githubusercontent.com/55134147/64601594-82e77f80-d3bd-11e9-8c94-9d5e7440e546.png)

However, if I move the "Find / Replace Using ReEx" element down to position 4 again and add another "Find / Replace Using ReEx" element at the end at position 5, the Expert Mode correctly keeps the sequence after klicking "OK" and "Edit ..." again:

![Unbenannt2](https://user-images.githubusercontent.com/55134147/64602160-8f200c80-d3be-11e9-87d4-a7d946cd8a16.png)

Running on Windows 10 Enterprise / 64, Version 1709, Build 16299.1268

**Comment by clechasseur** [comment]
This is _sort of_ as designed. The problem is that Simple Mode has a standardized element order. When you edit a custom command that is considered "simple" by the Settings app (e.g. it can be represented in Simple Mode), it will open in Simple Mode and the element order will be standardized.

There are a couple of solutions.
1. Check element order when determining whether a custom command is "simple"
2. Remember if custom command was edited in Expert Mode and if so, default to that mode when editing

I'm not entirely sure what's the best solution yet.

I'll keep this open and flag it as "enhancement".

**Comment by clechasseur** [comment]
Implemented in `master`. In version 17.1 and up, the Settings application will remember which edit mode was used for a custom command. Thus, editing it in Expert Mode will reopen it in that mode next time you edit.
